# Generated by Django 6.1.1 on 2026-09-20 10:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiftConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('box_design', models.CharField(max_length=100)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('qr_token', models.CharField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
