# Generated by Django 6.1.1 on 2026-09-19 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_product_cost_price_product_is_bestseller_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('hero_image', models.ImageField(upload_to='lookbooks/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LookbookItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.FloatField(help_text='X position in percentage (0-100)')),
                ('y_position', models.FloatField(help_text='Y position in percentage (0-100)')),
                ('lookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lookbook.lookbook')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookbook_items', to='products.product')),
            ],
        ),
    ]
