# Generated by Django 6.1.1 on 2026-09-20 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_gift_configuration'),
        ('products', '0005_product_is_mystery_box_product_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MysteryBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('is_revealed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mystery_box', to='orders.orderitem')),
                ('products', models.ManyToManyField(related_name='mystery_boxes', to='products.product')),
            ],
        ),
    ]
