# Generated by Django 6.1.1 on 2026-09-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review_is_approved_review_is_verified_reviewmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_mystery_box',
            field=models.BooleanField(default=False, help_text='Designates this product as a mystery box'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags for AI curation matching', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
